### ISSUE TITLE
Performance compared to catbox-redis

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/catbox-memory#39]
Hi,

I have a production app that uses catbox caching quite extensively. 95% of my values are stored with redis, since I am using multiple containers and I want them to use all the same cache. However I have some global values that are used that often, that I thought I can cache it on every container alone to improve read speed on these cache values.

During my load test it turned out, that catbox-redis (with latency on aws) is faster than catbox memory, which I found confusing.

Anyone experiences something similar or has an Idea why that is the case?

**Comment by cjihrig** [comment]
It's hard to say. Is there any additional info you can provide, like a self contained code sample showing catbox memory being really slow?

**Comment by KeKs0r** [comment]
I have only tested in my app between catbox-memory and catbox-redis and then ran a load test. I am not sure if it would have the same effect same contained. The function I was caching was a normal sequel query. If it would help, I can provide it, but not sure it would make a difference.
