### ISSUE TITLE
Seems not to be cluster-proof

### ISSUE THREAD

**Issue by gxapplications** [hapijs/catbox-memory#44]
When using this cache in cluster mode under PM2 (for hapi-rate-limit usage, in my case). I clearly see that the cache is not shared between my 4 instances.
Well, because I suppose it's pure memory, its limited to the process. It should be logical, but not told anywhere...

Am I right or there is a problem about this? Specific configuration?
If this cache cannot be cross-instance for cluster mode, I suggest to tell this in the main description of the module. I suppose some other catbox are cross-instance.

**Comment by hueniverse** [comment]
It is not shared by multiple instances. Feel free to suggest language to make this clearer as it will never support this use case.
