### ISSUE TITLE
Implementing a binary tree for storage and search would improve performance

### ISSUE THREAD

**Issue by hiddentao** [hapijs/catbox-memory#50]
The module uses the Javascript object (i.e. built-in hash table) to store items. With a very large no. of cache items this will become less efficient than using a binary search tree to store items.

**Comment by kanongil** [comment]
That seems like a dubious claim. A hash table will have a typical insertion complexity of `O(1)`, while a BST has a fixed `O(log(n))`.

**Comment by hiddentao** [comment]
@kanongil I was basing this on code kata I've completed where using a binary tree instead of a hash table saved the day for me. However, having researched this a bit more just now, the mathematical evidence supports your point of view more than mine.
