### ISSUE TITLE
hapi server exits immediately if using catbox-memory cache.

### ISSUE THREAD

**Issue by steevhise** [hapijs/catbox-memory#51]
catbox-memory now seems to make hapi crash completely silently.
versions: node 8.7.0,  hapi 16.6.2, catbox 9.0.0, catbox-memory 3.0.0

below is a very basic server which exits immediately with `Process finished with exit code 0`

```
const Hapi = require('hapi');
const Hoek = require('hoek');
const Mem = require('catbox-memory');

// basic server
const server = new Hapi.Server({
    cache: {
        engine: Mem,
        name: 'test',
        partition: 'test-partition'
    }
});

server.connection({ port: 7000 });

server.start((err) => {

    Hoek.assert(!err, err);
    console.log('Server started at: ' + server.info.uri);
});
```

commenting out the 
```
    cache: {
        engine: Mem,
        name: 'test',
        partition: 'test-partition'
    }
``` 
results in the server starting fine as usual.

**Comment by steevhise** [comment]
fwiw, I cloned the current repo and ran the tests and they all pass just fine.

**Comment by kanongil** [comment]
That version combination doesn't make any sense.

**Comment by hueniverse** [comment]
You need to pay attention to the new set of hapi v17 modules. Use the previous major version of this module.

**Comment by steevhise** [comment]
so you're saying 3.0.0 isn't compatible with hapi 16?

**Comment by steevhise** [comment]
also, it would be nice if there was some explanation when it exits.

**Comment by devinivy** [comment]
@steevhise yeah, that's right.  I wonder if this could be better expressed using a peer dependency on the relevant version of catbox.

**Comment by dhinklexo** [comment]
Did 3.0 get published accidentally? The [releases page](https://github.com/hapijs/catbox-memory/releases) show's 2.x.x being the current release, when npm is installing 3.0.0 by default.

**Comment by hueniverse** [comment]
We don't really uses releases consistently so it's never a good indication across hapijs modules. No accidents.
