### ISSUE TITLE
Large overhead from expires times when highly populated

### ISSUE THREAD

**Issue by kpdecker** [hapijs/catbox-memory#8]
Commonly seeing 20-40k timer instances due to a timer being created for each cache entry. Outside of the CPU overhead that this might incur (I don't know the node internals, other than that there is some sort of linked list going on), this does create a lot of memory overhead.

In one particular dump seeing 30megs+ of retained data for these timers, domains, protects, etc that are all associated with each timer instance.

Under our use pattern these timers commonly trigger at very similar times and it seems like with some smart bucketing and a prune setInterval or similar much of this overhead could be dramatically reduced.

**Comment by hueniverse** [comment]
This combines with #36 should be resolved by replacing all the individual timeouts with a single interval that checks what expired and cleans it up. When you ask for expired data, clean it. The interval should be configurable.

**Comment by hueniverse** [comment]
@geek @kanongil @cjihrig would love a review.
